name: Output Information
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "The repository is ${{ toJson(github.event) }}" 